[build]
base = "."
publish = "./site"
functions = "functions/"

[[redirects]]
    from = "/api"
    to = "/.netlify/functions/wowthatsbig"
    status = 200

[[redirects]]
    from = "/api/randomarray"
    to = "/.netlify/functions/randomarray"
    status = 200

[[redirects]]
    from = "/api/randomjoke"
    to = "/.netlify/functions/randomjoke"
    status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; font-src fonts.gstatic.com; style-src 'self' fonts.googleapis.com *.cloudfront.net *.jsdelivr.net 'unsafe-inline'; img-src * 'self' data:; script-src 'self' *.cloudfront.net;"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
